name: acq-mail-env
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - pyodbc=4.0.*
  - pymssql=2.1.*
  - sqlalchemy=1.4.*
  - pandas=1.4.*
  - openpyxl=3.0.*
  - scikit-learn=1.1.*
  - slack-sdk=3.17.*
  - pysftp=0.2.*
  - ipykernel=6.15.*
  - black=22.6.*
  - nltk=3.6.*
  - tabulate=0.8.*
  - xgboost=1.6.*
  - boto3=1.24.*
  - fsspec=2022.10.*
  - s3fs=2022.10.*
  - s3path=0.3.*
  - matplotlib=3.6.*
  - snowflake-connector-python=3.5.*
  - snowflake-sqlalchemy=1.4.*
  - pyarrow=10.0.*
  - xlsxwriter=3.1.*